!!python/object:argparse.Namespace
tabDiffusion: !!python/object:argparse.Namespace
  batch_size: 4096
  dropout: 0.0
  hidden_dim_layer:
  - 512
  - 256
  dim_t: 128
  num_timesteps: 1000
  gaussian_loss_type: kl
  lr: 0.001
  fold: 5
  is_y_cond: false
  epochs: 60000
  eval_freq: 10000
  print_freq: 5000
gt_graph: !!python/object:argparse.Namespace
  kwarg: None
SMOTE: !!python/object:argparse.Namespace
  k_neighbors: 5
AdaSyn: !!python/object:argparse.Namespace
  n_neighbors: 5
